version: '3.9'

services:
  app:
    build: .
    image: andreeaclmr/free-api-only:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:Free_API_Only
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources:/app/resources
    networks:
      - app-network

networks:
  app-network:
    driver: bridge